name: CI workflow
on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install devbox environment
        uses: jetify-com/devbox-install-action@v0.11.0
      - name:  Build Website
        run: |
          devbox run -- hugo
